[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
    "crossfont",
]

[profile.release]
strip = true
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
