[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
    "crossfont",
]

[profile.release]
lto = true
debug = 1
incremental = false
